development:
  adapter: postgresql
  database: Cassius
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: Cassius
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: Cassius
  pool: 5
  timeout: 5000